[package]
name = "synthette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_soft_float = "0.1.4"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib", "rlib"]
